-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 23:29:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_Funcionaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_Funcionaries` (
  `id_Funcionaries` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(10) NOT NULL,
  `cargo` VARCHAR(25) NOT NULL,
  `data_admissao` VARCHAR(10) NOT NULL,
  `salario` DOUBLE NOT NULL,
  PRIMARY KEY (`id_Funcionaries`),
  UNIQUE INDEX `id_Funcionaries_UNIQUE` (`id_Funcionaries` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `mydb`.`tb_Funcionaries`(nome, data_nascimento, cargo, data_admissao, salario)
VALUES ("Luana Cristina Bezana","22/02/1996","scrum master","06/07/2019",12982.00);

INSERT INTO `mydb`.`tb_Funcionaries`(nome, data_nascimento, cargo, data_admissao, salario)
VALUES ("Pedro Couventaris","16/03/1994","desenvolvedor senior","14/09/2015",8236.00);

INSERT INTO `mydb`.`tb_Funcionaries`(nome, data_nascimento, cargo, data_admissao, salario)
VALUES ("Filomena Goivinho","21/03/1956","desenvolvedora senior","25/10/2018",8224.00);

INSERT INTO `mydb`.`tb_Funcionaries`(nome, data_nascimento, cargo, data_admissao, salario)
VALUES ("Cleyton Bezana","15/09/1952","desenvolvedor pleno","14/04/2015",6824.00);

INSERT INTO `mydb`.`tb_Funcionaries`(nome, data_nascimento, cargo, data_admissao, salario)
VALUES ("Vanessa Cristina","28/08/1988","desenvolvedora junior","08/05/2020",1999.00);

SELECT * FROM `mydb`.`tb_Funcionaries`;

SELECT * FROM  `mydb`.`tb_Funcionaries` WHERE salario >2000;

SELECT * FROM  `mydb`.`tb_Funcionaries` WHERE salario <2000;

UPDATE `mydb`.`tb_Funcionaries` SET salario = 2500 WHERE id_Funcionaries = 5;