-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 23:55:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_Produtos` (
  `id_Produtos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `quantidade_estoque` INT NOT NULL,
  `disponibilidade` TINYINT NOT NULL,
  `marcas` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_Produtos`),
  UNIQUE INDEX `idtb_Produtos_UNIQUE` (`id_Produtos` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `mydb`.`tb_Produtos`(nome, valor, quantidade_estoque, disponibilidade, marcas)
VALUES ("Guitarra", 6000, 10, true, "EVH");
INSERT INTO `mydb`.`tb_Produtos`(nome, valor, quantidade_estoque, disponibilidade, marcas)
VALUES ("PS5", 4600, 1, true, "Sony");
INSERT INTO `mydb`.`tb_Produtos`(nome, valor, quantidade_estoque, disponibilidade, marcas)
VALUES ("Mochila", 349, 30, true, "Nike");
INSERT INTO `mydb`.`tb_Produtos`(nome, valor, quantidade_estoque, disponibilidade, marcas)
VALUES ("Palheta", 3, 100, true, "Dunlop");
INSERT INTO `mydb`.`tb_Produtos`(nome, valor, quantidade_estoque, disponibilidade, marcas)
VALUES ("Moletom", 400, 45, true, "Forever 21");
INSERT INTO `mydb`.`tb_Produtos`(nome, valor, quantidade_estoque, disponibilidade, marcas)
VALUES ("Pleaser", 750, 3, true, "PlayPole");
INSERT INTO `mydb`.`tb_Produtos`(nome, valor, quantidade_estoque, disponibilidade, marcas)
VALUES ("Kit Beleza", 240, 140, true, "Blz na Web");
INSERT INTO `mydb`.`tb_Produtos`(nome, valor, quantidade_estoque, disponibilidade, marcas)
VALUES ("Kit Panelas", 620, 32, true, "Tramontina");

SELECT * FROM `mydb`.`tb_Produtos`;

SELECT * FROM  `mydb`.`tb_Produtos` WHERE valor >500;

SELECT * FROM  `mydb`.`tb_Produtos` WHERE valor <500;

UPDATE `mydb`.`tb_Produtos` SET quantidade_estoque = 12 WHERE id_Produtos = 6;