-- MySQL Script generated by MySQL Workbench
-- Wed Apr 21 00:24:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_Alunes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_Alunes` (
  `id_Alunes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `serie` VARCHAR(15) NOT NULL,
  `materia` VARCHAR(15) NOT NULL,
  `professore` VARCHAR(15) NOT NULL,
  `média` FLOAT NOT NULL,
  PRIMARY KEY (`id_Alunes`),
  UNIQUE INDEX `idtb_Alunes_UNIQUE` (`id_Alunes` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `mydb`.`tb_Alunes`(nome, serie, materia, professore, média)
VALUES ("Amanda Souza", "quarta-série", "matemática", "Gioconda", 5.5);

INSERT INTO `mydb`.`tb_Alunes`(nome, serie, materia, professore, média)
VALUES ("Bruna Baltas", "sexta-série", "química", "Flávia", 7.8);

INSERT INTO `mydb`.`tb_Alunes`(nome, serie, materia, professore, média)
VALUES ("Carlos Eduardo", "terceira-série", "gramática", "Matheus", 6.9);

INSERT INTO `mydb`.`tb_Alunes`(nome, serie, materia, professore, média)
VALUES ("Danilo Anthony", "sétima-série", "matemática", "Gioconda", 6.4);

INSERT INTO `mydb`.`tb_Alunes`(nome, serie, materia, professore, média)
VALUES ("Gabriel Souza", "quarta-série", "matemática", "Gioconda", 8.5);

INSERT INTO `mydb`.`tb_Alunes`(nome, serie, materia, professore, média)
VALUES ("Miguel Silva", "nona-série", "história", "Alberto", 7.8);

INSERT INTO `mydb`.`tb_Alunes`(nome, serie, materia, professore, média)
VALUES ("Patricia Almeida", "segunda-série", "geografia", "Gustavo", 8.6);

INSERT INTO `mydb`.`tb_Alunes`(nome, serie, materia, professore, média)
VALUES ("Raquel Pereira", "oitava-série", "matemática", "Gioconda", 6.2);

SELECT * FROM `mydb`.`tb_Alunes`;

SELECT * FROM  `mydb`.`tb_Alunes` WHERE média >7.0;

SELECT * FROM  `mydb`.`tb_Alunes` WHERE média <7.0;

UPDATE `mydb`.`tb_Alunes` SET média = 7.8 WHERE id_Alunes = 3;